//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 数据提取.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MyTYPE                      130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_MAINPROGRESSBAR             199
#define IDR_CHILDROGRESSBAR             200
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDB_BITMAP2                     311
#define IDD_DIALOG1                     312
#define IDD_ProgressDlg                 312
#define IDD_DIALOG2                     313
#define IDD_DateTimeDlg                 313
#define IDB_BITMAP1                     314
#define IDD_DIALOG3                     315
#define IDD_DIALOG4                     316
#define IDD_DIALOG5                     317
#define IDD_DIALOG6                     318
#define IDD_StatisticLineDataToWord     319
#define IDD_DIALOG7                     320
#define IDC_PROGRESS1                   1000
#define IDC_DATETIMEPICKER1             1004
#define IDC_DATETIMEPICKER2             1005
#define IDC_Range                       1006
#define IDC_EDIT1                       1007
#define IDC_EDIT2                       1008
#define IDC_EDIT3                       1009
#define IDC_BUTTON1                     1009
#define IDC_EDIT4                       1010
#define IDC_RADIO1                      1010
#define IDC_BUTTON2                     1010
#define IDC_RADIO2                      1011
#define IDC_EDIT5                       1011
#define IDC_CHECK1                      1012
#define IDC_BUTTON3                     1012
#define IDC_EDIT7                       1012
#define IDC_COMBO1                      1013
#define IDC_EDIT8                       1013
#define IDC_RADIO3                      1014
#define IDC_COMBO2                      1014
#define IDC_EDIT9                       1014
#define IDC_RADIO4                      1015
#define IDC_EDIT6                       1015
#define IDC_MFCLINK1                    1016
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BUTTON2                      32771
#define ID_BUTTON3                      32772
#define ID_RemoveData                   32773
#define ID_RemovePathOfData             32774
#define ID_EDIT3                        32775
#define ID_Clear                        32776
#define ID_DisplayVelocity              32777
#define ID_DisplayGoodData              32778
#define ID_SmoothVelocity               32780
#define ID_PropertyWnd                  32781
#define ID_Stop                         32783
#define ID_Back                         32784
#define ID_StartPoint                   32785
#define ID_FinishPoint                  32786
#define ID_Start                        32787
#define ID_SelectPointSlider            32788
#define ID_OutDataLine                  32789
#define ID_MainFigure                   32790
#define ID_Advance                      32791
#define ID_ReadData                     32792
#define ID_DisplayGravData              32793
#define ID_COMBO_Year                   32795
#define ID_COMBO_Month                  32796
#define ID_COMBO_Day                    32798
#define ID_SelectStartData              32799
#define ID_SelectEndDate                32800
#define ID_PROGRESS1                    32801
#define ID_SmoothGravity                32802
#define ID_BGCorrect                    32803
#define ID_BUTTON4                      32804
#define ID_GetGPUProperty               32804
#define ID_TimeCorrect                  32805
#define ID_OutPutFGA                    32806
#define ID_OutPutBGA                    32807
#define ID_ExtractGPS                   32808
#define ID_CheckAmend                   32809
#define ID_MatchGPS_GRAV                32810
#define ID_CreateWordReport             32811
#define ID_32813                        32813
#define ID_Help                         32814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        322
#define _APS_NEXT_COMMAND_VALUE         32817
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
